#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

const int SCREEN_WIDTH = 320;
const int SCREEN_HEIGHT = 240;
const int FPS = 60;
const int FRAME_DELAY = 1000 / FPS;
const int MOUSE_BUTTON_SIZE = 256;
#endif // CONSTANTS_H_INCLUDED
